#pragma once

#define SS_FUNCTION_W ANSI_TO_TCHAR(__FUNCTION__)

SHAKESLASH_API DECLARE_LOG_CATEGORY_EXTERN(SSLogCharacter, Log, All);
SHAKESLASH_API DECLARE_LOG_CATEGORY_EXTERN(SSLogMode, Log, All);
SHAKESLASH_API DECLARE_LOG_CATEGORY_EXTERN(SSLogUtility, Log, All);